Add bookings
AssortedCaret/java-shareit pull request #3
Opened 2023-06-09 14:37 UTC by AssortedCaret

2023-06-10 13:57 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично. 
После правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" и "Можно лучше"), присылай работу на продолжение проверки.
Спасибо.

2023-06-10 13:57 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer"})
Отлично:

Отлично, что ты сам нашёл решение для данной проблемы (при этом отмечу, что в реальном проекте скорее всего это было бы промежуточное решение и потребовалось бы искать и исправлять причину на более базовом уровне, примерно как указано здесь: https://stackoverflow.com/a/58490797 - но это далеко отходит от целей данного учебного проекта и твой вариант вполне рабочий).

2023-06-10 13:57 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/Service/ItemServiceImpl.java
> +        for (Item it : itemRepository.findAll()) {
Надо исправить:

Здесь происходит выборка всех-всех вещей из репозитория лишь для того, чтобы отобрать только вещи, принадлежащие одному пользователю, если вещей будет много миллионов (как на крупных площадках), а запросов будет также много в минуту, это может заставить сервис "зависнуть". 

Нужно попробовать написать JPQL-запрос ИЛИ ещё проще - запросный метод с JOIN-ом таблиц items и users и фильтрацией по userId в поле owner на уровне репозитория вещей и использовать его здесь.

А затем действовать примерно так:
```
//для полученного списка вещей данного (по userId) пользователя, допустим, названного 
List<Item> items

//выгружаем комментарии, связанные с данными items, группируем их по вещам и конвертируем в dto, 
//получаем
Map<Item, List<Comment>> comments 

//Далее выгружаем подтвержденные бронирования для данных items, отсортированные по дате начала
//и группируем их по вещам, получаем, например
Map<Item, List<Booking>> approvedBookings

//Далее для каждой вещи находим последнее и следующее бронирование, а также комментарии
//и формируем результат в форме DTO
List<ItemDto> results
```

Аналогичный комментарий справедлив для других методов поиска в слое сервисов. 
При этом мне достаточно, что ты продемонстрируешь только на примере правки данного метода понимание того, как избегать поиска через findAll() и проводить сужение (фильтрации) поиска до необходимого минимума данных из БД.
Т.к. переделывать аналогичным образом другие методы может быть весьма трудозатратно и избыточно с т.з. обучения=).

2023-06-10 17:35 UTC, AssortedCaret commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Я лучше оставлю данный фрагмент настроек для себя на будущее.

2023-06-10 19:09 UTC, AssortedCaret commented on src/main/java/ru/practicum/shareit/item/Service/ItemServiceImpl.java
> +        for (Item it : itemRepository.findAll()) {
Я понял замечание по поводу времени исполнения запроса и работы самого метода. Я добавил в itemRepository новый запрос, который сразу сможет выдавать нам необходимые вещи с правильным собственником, что сократит время работы метода. 
Но дальше я не понял зачем нам нужно создавать мапы с различными данными(Map<Item, List<Comment>> comments; Map<Item, List<Booking>> approvedBookings), если я для конкретной вещи, путем запроса к БД, получаю необходимую нам информацию(с использованием сужения поиска) и сразу добавляю ItemDto в List? Просто из мап тоже надо будет доставать всю информацию и добавлять всю инфу из них в один объект(Item / ItemDto).
Просто у меня вроде и так всё что можно достать из БД с сужением поиска, достается из БД, и как тогда создание и работа с мапами ускорит работу метода?

2023-06-11 09:11 UTC, zgreen3 commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Да, конечно. Я имел ввиду, что этот фрагмент лучше раскомментировать, т.к. в тестах всё равно будет использоваться профиль с настройками БД H2 далее.

2023-06-11 09:14 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/Service/ItemServiceImpl.java
> +        for (Item it : itemRepository.findAll()) {
> дальше я не понял зачем нам нужно создавать мапы с различными данными(Map<Item, List> comments; Map<Item, List> approvedBookings), если я для конкретной вещи, путем запроса к БД, получаю необходимую нам информацию(с использованием сужения поиска) и сразу добавляю ItemDto в List? Просто из мап тоже надо будет доставать всю информацию и добавлять всю инфу из них в один объект(Item / ItemDto)

Да, можно использовать и сужение поиска, я выше только предложил вариант с мапами (может, несколько ультимативно сформулировал, но не имел ввиду, что это единственный возможный вариант), главное, чтобы из кода этого метода ушёл внешний цикл for (Item it : itemRepository.findAll()) { ... } если запросы к БД будут НЕ для каждого Item it, а сразу для многих, то любой вариант подойдёт.

2023-06-11 09:22 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-06-11 09:22 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllItemWhereOwner(Long userId);
Отлично:

Именно такой запрос имелся ввиду, отлично (кстати, для информации: если не ошибаюсь - не проверял в коде, можно также было использовать здесь примерно такой запросный метод: `List<Item> findByOwner_IdEquals(Long userId);` ).

2023-06-11 09:22 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/Service/ItemServiceImpl.java
> +        for (Item it : itemRepository.findAllItemWhereOwner(userId)) {
Отлично:

Точно, такой код теперь оптимальнее работает с БД, +в целом, согласен с твоим комментарием - здесь можно обойтись без мап.

2023-06-11 13:02 UTC, merged