Add item requests
AssortedCaret/java-shareit pull request #4
Opened 2023-06-24 20:01 UTC by AssortedCaret

2023-06-26 23:03 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ и видно, что хорошо проработан, отлично. 
После принятия к сведению комментариев, присылай работу на завершение проверки.
Спасибо.

2023-06-26 23:03 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +@DataJpaTest
Отлично:

Вижу, что ты также разобрался с DataJpaTest-ами, замечательно!

Кстати, советую в тестовых методах при длинных инициализациях (в данном классе всё нормально, инициализации весьма краткие, это просто примечание для информации)) до вызова тестируемого метода писать в тестовом-методе комментарий "//given", над самим тестируемым методом - "//when", а перед группой ассёртов - "//then" (https://en.wikipedia.org/wiki/Given-When-Then#:~:text=Given-When-Then%20(GWT,words%20given%2C%20when%20and%20then. , https://martinfowler.com/bliki/GivenWhenThen.html), такой подход поможет быстро визуально выделять нужные части длинного тестового метода, а если на проекте будет потом использоваться Cucumber или подобный BDD-фреймворк, то его применение будет привычнее команде, привыкшей так структурировать юнит-тесты.

2023-06-26 23:03 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Отлично:
Вижу, что все основные тесты, необходимые по ТЗ, у тебя в проекте присутствуют, так держать!

При этом, поскольку не обнаружил в коде проекта кастомных реализаций сериализации / десериализации в JSON (точнее, классов с аннотацией @JsonComponent), то требование ТЗ про "реализацию тестов для работы с JSON для DTO в приложении с помощью аннотации @JsonTest" можно считать не относящимся к данному проекту=). В любом случае, советую ознакомиться с возможностями применения этой аннотации в Spring Boot-проектах, см. краткое описание с примером, на англ. яз., например, тут: https://www.arhohuttunen.com/spring-boot-jsontest/

2023-06-27 09:21 UTC, AssortedCaret commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    List<ItemRequest> getAllItemRequestForUser(Long userId);
Поменял значение ORDER BY

2023-06-27 18:50 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично!
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.
Успехов в освоении важной (и вполне посильной)) темы про докер-контейнеры!

2023-06-27 20:24 UTC, merged